# Generated by Django 4.2.4 on 2023-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lead_actor', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
